services:
    php8site:
        build:
            context: .
        image: antoniomedeiros/long-running-php
        container_name: apache-php
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:80"
        networks:
            - my-app-network

    db:
        image: clue/json-server
        container_name: json-server
        volumes:
            - ./data/db.json:/data/db.json
        ports:
            - "8081:80"
        networks:
            - my-app-network

networks:
    my-app-network:
        driver: bridge